version: 1
formatters:
  brief:
    format: '%(name)s - %(levelname)s - %(message)s'
  precise:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%m/%d/%Y %I:%M:%S %p %Z'
handlers:
  console:
    class : logging.StreamHandler
    formatter: brief
    level   : INFO
    stream  : ext://sys.stdout
  file:
    class : logging.handlers.RotatingFileHandler
    formatter: precise
    filename: /logs/backend.log
    maxBytes: 10485760
    backupCount: 5
loggers:
  backendLogger:
    level: DEBUG
    handlers: [console, file]
    propagate: no
root:
  level: DEBUG
  handlers: [console]